swagger: '2.0'
info:
  version: '1.0'
  title: My tutorial project
  description: An app to manage Tutorials
host: localhost:3000
basePath: /
tags:
  - name: Tutorials
    description: API for tutorial
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  JWT:
    type: apiKey
    in: header
    name: Authorization

paths:
  /tutorials:
    get:
      tags:
        - Tutorials
      summary: Get all tutorials in system
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Tutorial'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/500Response'

    post:
      summary: Create tutorials in system
      tags:
        - Tutorials
      parameters:
        - name: Tutorials
          in: body
          description: Tutorial that we want to create
          schema:
            $ref: '#/definitions/TutorialCreateBody'
      produces:
        - application/json
      responses:
        '201':
          description: New tutorial is created
          schema:
            $ref: '#/definitions/Tutorial'
        '400':
          description: 'Invalid tutorial Id'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/500Response'

  /tutorials/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the tutorial
        type: string
    delete:
      summary: Delete tutorial with given ID
      tags:
        - Tutorials
      responses:
        '200':
          description: Tutorial is deleted
        '404':
          description: 'Tutorial not found'
          schema:
            $ref: '#/definitions/404Response'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/500Response'

    patch:
      summary: Update tutorial with give ID
      tags:
        - Tutorials
      parameters:
        - name: Tutorials
          in: body
          description: Tutorial that we want to update
          schema:
            $ref: '#/definitions/TutorialCreateBody'
      responses:
        '204':
          description: Tutorial is updated
        '404':
          description: 'Tutorial not found'
          schema:
            $ref: '#/definitions/404Response'
        '400':
          description: 'Invalid tutorial Id'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'

    get:
      tags:
        - Tutorials
      summary: Get tutorial By ID
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Tutorial'
        '404':
          description: 'Tutorial not found'
          schema:
            $ref: '#/definitions/404Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'

  /users:
    post:
      summary: Create User
      tags:
        - User
      parameters:
        - name: CreateUser
          in: body
          description: Enter user details
          schema:
            $ref: '#/definitions/UserCreateBody'
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid user details
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/500Response'
    patch:
      summary: Update user
      tags:
        - User
      parameters:
        - name: updateUser
          in: body
          description: Update user.
          schema:
            $ref: '#/definitions/UserUpdateBody'
      produces:
        - application/json
      responses:
        '204':
          description: user is updated
        '404':
          description: 'User not found'
          schema:
            $ref: '#/definitions/404Response'
        '400':
          description: 'Invalid user details'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/500Response'
      security:
        - JWT: []

  /users/oauth/reset-password:
    patch:
      summary: Reset user password
      tags:
        - User
      parameters:
        - name: resetPassord
          in: body
          description: update password using old password
          schema:
            $ref: '#/definitions/UserResetPassword'
      responses:
        '200':
          description: OK
        '400':
          description: 'Invalid password'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'

  /users/oauth/forget-password:
    parameters:
      - name: email
        in: path
        required: true
        description: Email of the user
        type: string
    post:
      summary: Forget password using user id through email otp
      tags:
        - User

      responses:
        '200':
          description: OK
        '404':
          description: 'User not found'
          schema:
            $ref: '#/definitions/404Response'
        '400':
          description: 'Invalid User email'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'

    patch:
      summary: Reset password using otp
      tags:
        - User
      parameters:
        - name: User
          in: body
          description: User password reset using token
          schema:
            $ref: '#/definitions/UserResetPassword'
      responses:
        '204':
          description: Password is updated
        '400':
          description: 'Invalid token'
          schema:
            $ref: '#/definitions/400Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'

  /users/oauth/token:
    post:
      summary: Login user into system
      tags:
        - User
      parameters:
        - name: 'email'
          in: 'query'
          description: 'Enter email for login'
          required: true
          type: 'string'
        - name: 'password'
          in: 'query'
          description: 'Enter password for login'
          required: true
          type: 'string'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OauthToken'
        '404':
          description: 'User not found'
          schema:
            $ref: '#/definitions/404Response'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/500Response'
      security:
        - JWT: []

definitions:
  Tutorial:
    required:
      - _id
      - title
      - description
      - createdAt
      - updatedAt
      - published
    properties:
      _id:
        type: string
        format: uuid
        uniqueItems: true
      title:
        type: string
      description:
        type: string
      published:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  TutorialCreateBody:
    required:
      - title
      - description
      - published
    properties:
      title:
        type: string
      description:
        type: string
      published:
        type: boolean

  User: 
    required:
      - _id 
      - firstName
      - lastName
      - email
      - password
    properties:
      _id:
        type: string
        format: uuid
        uniqueItems: true
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      
  UserCreateBody:
    required:
      - firstName
      - lastName
      - email
      - password

    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string

  UserUpdateBody:
    required:
      - firstName
      - lastName
      - email

    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string

  UserResetPassword:
    required:
      - currentpassword
      - newPassword
    properties:
      currentpassword:
        type: string
      newPassword:
        type: string

  OauthToken:
    required:
      - userName
      - password
    properties:
      userName:
        type: string
      password:
        type: string

  500Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  404Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  400Response:
    type: object
    required:
      - message
    properties:
      message:
        type: string
