swagger: '2.0'
info:
  version: 1.0.0
  title: My Tutorial project!!!
host: localhost:8080
tags:
- description: API for design tutorial
schemes:
- http
consumes:
- application/yaml
produces:
- application/yaml
paths:
  tutorial:
    parameters:
    - name: id
      in: path
      required: true
      description: ID of tutorial that we want to find
      type: integer
    get:
      tags:
      - Tutorial
      summary: Get all tutorial in system
      responses:
        '200':
          description: Tutorial data
          schema:
            $ref: '#/definitions/tutorial'
    post:
      summary: create tutorial in system
      tags:
      - Tutorial
      description: Add new tutorial in system
      parameters:
      - name: tutorial
        in: body
        schema:
          $ref: '#/definitions/tutorial'
      produces:
      - application/yaml
      responses:
        '200':
          description: New tutorial is created
          schema:
            $ref: '#/definitions/tutorial'
    delete:
      summary: Delete tutorial with given ID
      tags:
      - Tutorial
      responses:
        '200':
          description: tutorial is deleted
          schema:
            $ref: '#/definitions/tutorial'
    patch:
      summary: Update tutorial with give ID
      tags:
      - Tutorial
      parameters:
      - name: tutorial
        in: body
        schema:
          $ref: '#/definitions/tutorial'
      responses:
        '200':
          description: tutorial is updated!!
          schema:
            $ref: '#/definitions/tutorial'
definitions:
  tutorial:
    required:
    - UUID
    - createDate
    - updateDate
    properties:
      UUID:
        type: string
        uniqueItems: true
      isPublic:
        type: boolean
      createDate:
        type: string
        format: date-time
      updateDate:
        type: string
        format: date-time
